# West manifest file (west.yml)
# Corrected: Removed self: path: config to match repo structure

manifest:
  # Defines remote locations (servers/organizations) where projects can be found.
  remotes:
    # 'zmkfirmware' is a shorthand name for the main ZMK GitHub organization.
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  # Lists the projects (repositories) to be managed by west.
  projects:
    # The main ZMK firmware repository.
    - name: zmk
      remote: zmkfirmware # Use the 'zmkfirmware' remote defined above.
      revision: main # Track the 'main' branch of the ZMK repository.
      import: app/west.yml # IMPORTANT: This imports dependencies defined within ZMK itself (like Zephyr).

# Note: The 'self:' block has been removed as config files are in the root.
