# ZMK Build Workflow using official build container
# Corrected version: Removed 'Force refresh west.yml' step

name: Build ZMK Firmware

# Triggers: Run on push/pull request to main, or manually (workflow_dispatch)
on:
  push:
    branches: [ "main" ] # Adjust branch name if needed
  pull_request:
    branches: [ "main" ] # Adjust branch name if needed
  workflow_dispatch: # Allows manual triggering from Actions tab

jobs:
  build:
    # Use the official ZMK build container environment
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable

    # Define the build matrix for different boards/shields
    strategy:
      fail-fast: false
      matrix:
        # ================= IMPORTANT ==================
        # Customize this section for your keyboard(s)!
        # - Replace 'nice_nano_v2' with your actual board name.
        # - Replace 'corne_left', 'corne_right' with your actual shield names
        #   (matching your .conf/.keymap files in the root).
        # - Add/remove 'include' blocks as needed.
        # ==============================================
        include:
          - board: nice_nano_v2 # <--- EXAMPLE: CHANGE THIS
            shield: corne_left  # <--- EXAMPLE: CHANGE THIS
          - board: nice_nano_v2 # <--- EXAMPLE: CHANGE THIS
            shield: corne_right # <--- EXAMPLE: CHANGE THIS
          # Add more blocks here if needed

    # Steps to execute for each matrix combination
    steps:
      # Step 1: Check out the user's configuration repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Verify essential commands are present in the container (Debug)
      - name: Verify essential commands
        run: |
          echo "--- Checking west ---"
          command -v west || echo "ERROR: west not found"
          echo "--- Checking cmake ---"
          command -v cmake || echo "ERROR: cmake not found"
          echo "--- Checking ninja ---"
          command -v ninja || echo "ERROR: ninja not found"
          echo "--- Checking arm-none-eabi-gcc ---"
          command -v arm-none-eabi-gcc || echo "ERROR: gcc not found"
          echo "--- PATH ---"
          echo $PATH

      # Step 3: Initialize the west workspace based on west.yml in the repo root
      - name: Initialize west workspace
        run: |
          if [ ! -f west.yml ]; then
            echo "ERROR: west.yml file not found in the repository root!"
            exit 1
          fi
          west init -l

      # Step 4: Update west dependencies (fetch ZMK, Zephyr, etc.) with shell tracing
      - name: Update west dependencies
        run: |
          set -x # Optional: keep for debugging shell commands
          west update # REMOVE --force from this line

      # Step 5: List files after update (Debug) - Check if zmk/zephyr exist now
      - name: List files after west update
        run: |
          echo "Listing directory contents after west update:"
          pwd
          ls -la
          echo "--- Checking for zmk directory ---"
          ls -la zmk || (echo "zmk directory not found (after update)" && exit 1)
          echo "--- Checking for zephyr directory ---"
          ls -la zephyr || (echo "zephyr directory not found (after update)" && exit 1)
      # Step 6: Build the firmware using matrix variables
      - name: Build firmware
        run: |
          echo "Building for board: ${{ matrix.board }} shield: ${{ matrix.shield }}"
          # Build command arguments:
          # -s zmk/app : Explicitly point to ZMK source code
          # -p : Pristine build (clean first)
          # -b : Target board from matrix
          # -d : Output build directory (using shield name)
          # -- : Separator for CMake/KConfig args
          # -DSHIELD= : Target shield name from matrix
          # -DZMK_CONFIG= : Path to user config dir (repo root in this case)
          west build -s zmk/app -p -b ${{ matrix.board }} -d build/${{ matrix.shield }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}"

      # Step 7: Archive the compiled firmware (.uf2 file)
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          # Name for the downloadable artifact zip file
          name: firmware-${{ matrix.board }}-${{ matrix.shield }}
          # Path to the firmware file within the build directory
          path: build/${{ matrix.shield }}/zephyr/zmk.uf2

